In [1]:
import numpy as np
import pandas as pn
import sklearn
import matplotlib

In [2]:
data = pn.read_csv('~/anaconda3/Kurs_project_task/train.csv')

In [3]:
data.describe()

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Social_1,Social_2,Social_3,Healthcare_1,Helthcare_2,Shops_1,Price
count,10000.00000,10000.000000,10000.000000,10000.000000,7887.000000,10000.000000,10000.000000,10000.000000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,5202.000000,10000.000000,10000.000000,10000.000000
mean,8383.40770,50.400800,1.890500,56.315775,37.199645,6.273300,8.526700,12.609400,3.990166e+03,0.118858,24.687000,5352.157400,8.039200,1142.904460,1.319500,4.231300,214138.857399
std,4859.01902,43.587592,0.839512,21.058732,86.241209,28.560917,5.241148,6.775974,2.005003e+05,0.119025,17.532614,4006.799803,23.831875,1021.517264,1.493601,4.806341,92872.293865
min,0.00000,0.000000,0.000000,1.136859,0.370619,0.000000,1.000000,0.000000,1.910000e+03,0.000000,0.000000,168.000000,0.000000,0.000000,0.000000,0.000000,59174.778028
25%,4169.50000,20.000000,1.000000,41.774881,22.769832,1.000000,4.000000,9.000000,1.974000e+03,0.017647,6.000000,1564.000000,0.000000,350.000000,0.000000,1.000000,153872.633942
50%,8394.50000,36.000000,2.000000,52.513310,32.781260,6.000000,7.000000,13.000000,1.977000e+03,0.075424,25.000000,5285.000000,2.000000,900.000000,1.000000,3.000000,192269.644879
75%,12592.50000,75.000000,2.000000,65.900625,45.128803,9.000000,12.000000,17.000000,2.001000e+03,0.195781,36.000000,7227.000000,5.000000,1548.000000,2.000000,6.000000,249135.462171
max,16798.00000,209.000000,19.000000,641.065193,7480.592129,2014.000000,42.000000,117.000000,2.005201e+07,0.521867,74.000000,19083.000000,141.000000,4849.000000,6.000000,23.000000,633233.466570

Поменял местами этажность и этаж квартиры, там где этаж превышает этажность

In [4]:
dt = data.loc[data['Floor'] > data['HouseFloor']]

In [5]:
dt['Floor'], dt['HouseFloor'] = dt['HouseFloor'],dt['Floor']

/home/pavel/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [6]:
data.loc[data['Floor'] > data['HouseFloor']] = dt

далее выровнял соотношение общей площади к жилой площади и площади кухни исходя из того, что 
    для однокомнатной квартиры установлены особые требования по количеству квадратных метров в жилой комнате - 14, тогда как в двух- и более комнатных жилищах планка поднята выше - до 16 для общей комнаты и 9 - для остальных жилых помещений.
    Размер спальни для всех квартир должен быть не менее восьми квадратных метров.
    Для кухни в двухкомнатной квартире установлены минимальные значения в 8 квадратных метров и, если речь идет о зонировании помещения, то 6 метров для зоны кухни в помещении столовой.
    В однокомнатной квартире разрешается устраивать кухни не менее шести метров и кухни ниши (5 метров).
http://gsps.ru/poleznoe/minimalnaya-ploshchad-pomeshcheniy-kvartiry.php

In [7]:
dt1 = data.loc[data['LifeSquare']>data['Square']]

In [9]:
dt1['LifeSquare'] = dt1['Square'] - dt1['KitchenSquare']

/home/pavel/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [19]:
data.loc[data['Rooms']==1].loc[data['LifeSquare']<12]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Healthcare_1,Helthcare_2,Shops_1,Shops_2,Price
160,3522,6,1.0,66.419841,3.987101,1.0,1.0,2.0,1977,0.243205,B,B,5,1564,0,540.0,0,0,B,193361.229815
270,15215,17,1.0,46.692974,5.941401,1.0,1.0,7.0,2015,0.000000,B,B,18,3374,5,620.0,1,2,B,212290.684086
363,15751,9,1.0,44.171793,1.251846,1.0,11.0,18.0,2017,0.161532,B,B,25,5648,1,30.0,2,4,B,134910.715588
477,8849,45,1.0,63.419553,2.286357,1.0,1.0,3.0,1977,0.195781,B,B,23,5212,6,NaN,3,2,B,325600.765809
527,2141,56,1.0,53.733677,4.323046,1.0,1.0,24.0,2015,0.000000,B,B,23,5067,4,NaN,2,6,B,208773.977243
674,10631,88,1.0,42.571618,1.941521,1.0,1.0,6.0,1977,0.127376,B,B,43,8429,3,NaN,3,9,B,130374.241595
695,1867,30,1.0,54.626206,4.651397,1.0,3.0,4.0,1977,0.000078,B,B,22,6398,141,1046.0,3,23,B,87456.520038
707,4345,62,1.0,49.275155,1.377284,1.0,1.0,5.0,2020,0.072158,B,B,2,629,1,NaN,0,0,A,135353.885620
734,4319,62,1.0,51.815214,4.203073,1.0,1.0,6.0,1977,0.072158,B,B,2,629,1,NaN,0,0,A,137880.620962
765,7060,27,1.0,38.651043,5.822657,1.0,7.0,17.0,1977,0.011654,B,B,4,915,0,NaN,0,0,B,103210.010325
850,2470,6,1.0,43.312025,1.404493,1.0,11.0,17.0,1977,0.243205,B,B,5,1564,0,540.0,0,0,B,128588.741321
1169,14866,6,1.0,38.818170,5.927865,1.0,17.0,18.0,1977,0.243205,B,B,5,1564,0,540.0,0,0,B,131405.866884
1175,3527,9,1.0,72.035396,2.358992,1.0,1.0,5.0,1977,0.161532,B,B,25,5648,1,30.0,2,4,B,191744.615408
1214,6366,6,1.0,47.804946,2.553024,1.0,6.0,25.0,1977,0.243205,B,B,5,1564,0,540.0,0,0,B,133552.372112
1316,11526,27,1.0,4.633498,1.969969,1.0,1.0,18.0,1977,0.011654,B,B,4,915,0,NaN,0,0,B,107604.269441
1410,1843,74,1.0,49.635712,3.411048,1.0,1.0,4.0,1977,0.309479,B,B,35,7715,4,990.0,0,6,B,146838.036852
1504,2967,1,1.0,62.494611,3.489694,0.0,0.0,1.0,1977,0.007122,B,B,1,264,0,NaN,0,1,B,193568.854208
1608,10202,6,1.0,2.596351,4.604943,1.0,3.0,25.0,2014,0.243205,B,B,5,1564,0,540.0,0,0,B,137597.601458
1673,12335,9,1.0,60.022123,2.858369,1.0,1.0,9.0,1977,0.161532,B,B,25,5648,1,30.0,2,4,B,176731.431750
1800,13113,27,1.0,37.805231,2.228592,11.0,0.0,6.0,2015,0.017647,B,B,2,469,0,NaN,0,0,B,137402.092529
1918,13603,63,1.0,127.651237,2.609712,1.0,8.0,17.0,2016,0.238617,B,B,26,3889,6,705.0,3,6,B,594565.299770
2224,3746,62,1.0,46.722042,1.944446,1.0,11.0,12.0,2018,0.072158,B,B,2,629,1,NaN,0,0,A,133721.121715
2309,10285,30,1.0,32.271741,3.386009,1.0,4.0,19.0,1977,0.000078,B,B,22,6398,141,1046.0,3,23,B,105921.018210
2418,5989,6,1.0,39.251773,2.981582,1.0,17.0,25.0,2016,0.243205,B,B,5,1564,0,540.0,0,0,B,136206.666782
2430,1317,6,1.0,51.460538,4.763693,1.0,25.0,25.0,1977,0.243205,B,B,5,1564,0,540.0,0,0,B,142065.034795
2665,8997,74,1.0,43.227719,1.726270,1.0,9.0,17.0,2016,0.075779,B,B,6,1437,3,NaN,0,2,B,154565.271940
2842,3142,6,1.0,39.145322,4.083905,1.0,8.0,17.0,1977,0.243205,B,B,5,1564,0,540.0,0,0,B,116981.443099
2860,12542,1,1.0,44.204418,1.789086,1.0,6.0,17.0,1977,0.007122,B,B,1,264,0,NaN,0,1,B,160181.048031
2898,5497,58,1.0,37.686426,4.977769,1.0,2.0,17.0,1977,0.437885,B,B,23,5735,3,1084.0,0,5,B,72950.870871
2906,10404,6,1.0,43.613432,3.668460,1.0,3.0,17.0,2016,0.243205,B,B,5,1564,0,540.0,0,0,B,128710.472293
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6609,13491,0,1.0,38.178277,0.370619,0.0,17.0,19.0,2016,0.006076,B,B,30,5285,0,645.0,6,6,B,105134.286994
7028,13440,6,1.0,78.432890,4.044174,1.0,1.0,2.0,1977,0.243205,B,B,5,1564,0,540.0,0,0,B,222826.758816
7045,15209,83,1.0,41.527079,2.077811,1.0,1.0,17.0,1977,0.007720,B,B,38,4788,2,NaN,0,4,B,214393.174037
7056,5575,27,1.0,41.941912,4.437475,0.0,0.0,10.0,2016,0.211401,B,B,9,1892,0,NaN,0,1,B,113350.022423
7068,15346,30,1.0,37.387578,4.699898,1.0,14.0,22.0,1977,0.000078,B,B,22,6398,141,1046.0,3,23,B,109553.129485
7221,5306,96,1.0,49.462997,1.417155,1.0,8.0,15.0,2016,0.041116,B,B,53,14892,4,NaN,1,4,B,119791.098164
7288,59,27,1.0,27.181473,10.924281,8.0,10.0,25.0,2014,0.072158,B,B,2,629,1,NaN,0,0,A,75170.813107
7452,8626,1,1.0,47.195748,1.168791,1.0,19.0,24.0,1977,0.007122,B,B,1,264,0,NaN,0,1,B,170718.296542
7719,10079,59,1.0,48.232741,3.288779,1.0,15.0,17.0,2017,0.019509,B,B,37,7687,11,176.0,5,5,B,207086.637307
7756,1680,58,1.0,47.889736,3.605019,1.0,3.0,17.0,1977,0.437885,B,B,23,5735,3,1084.0,0,5,B,122731.005950
7767,6927,21,1.0,16.117154,8.822988,0.0,2.0,5.0,1965,0.194489,B,B,47,8004,3,125.0,3,5,B,79913.267856
7897,10635,21,1.0,18.983962,11.419796,2.0,1.0,5.0,1967,0.194489,B,B,47,8004,3,125.0,3,5,B,112411.221700
8065,7669,34,1.0,43.873302,1.973848,1.0,13.0,17.0,2015,0.069753,B,B,53,13670,4,NaN,1,11,B,204863.503174
8220,8194,30,1.0,42.065862,5.624248,1.0,13.0,17.0,1977,0.000078,B,B,22,6398,141,1046.0,3,23,B,126976.982021
8283,15744,34,1.0,1.988943,2.642219,1.0,4.0,21.0,1977,0.069753,B,B,53,13670,4,NaN,1,11,B,458378.777006
8452,14380,58,1.0,40.525820,4.174627,1.0,16.0,17.0,1977,0.437885,B,B,23,5735,3,1084.0,0,5,B,116642.983817
8556,16575,27,1.0,32.712359,11.047605,13.0,8.0,25.0,2016,0.072158,B,B,2,629,1,NaN,0,0,A,94433.038958
8715,1936,74,1.0,53.835574,1.185864,0.0,7.0,7.0,2018,0.075779,B,B,6,1437,3,NaN,0,2,B,185976.351147
8886,2056,9,1.0,47.301790,5.125908,1.0,1.0,7.0,1977,0.161532,B,B,25,5648,1,30.0,2,4,B,138880.254465
8908,10684,22,1.0,41.872590,2.347250,1.0,1.0,3.0,1977,0.118537,B,B,30,6207,1,1183.0,1,0,B,136609.809831
9177,13951,45,1.0,39.225914,2.372105,1.0,24.0,24.0,2017,0.195781,B,B,23,5212,6,NaN,3,2,B,271893.118572
9192,1754,6,1.0,61.978423,3.943299,1.0,1.0,1.0,1977,0.243205,B,B,5,1564,0,540.0,0,0,B,177116.339701
9294,6782,45,1.0,2.954309,5.257278,1.0,1.0,3.0,1977,0.195781,B,B,23,5212,6,NaN,3,2,B,438005.182323
9299,8687,48,1.0,42.840915,2.608669,1.0,17.0,19.0,1977,0.041125,B,B,46,9515,5,NaN,1,10,B,236378.466217
9396,3745,30,1.0,42.457169,3.259832,1.0,10.0,25.0,2014,0.000078,B,B,22,6398,141,1046.0,3,23,B,155348.833619
9576,7389,23,1.0,52.028804,4.295819,0.0,8.0,9.0,1977,0.014073,B,B,2,475,0,NaN,0,0,B,98638.755928
9613,7657,38,1.0,4.502784,4.618547,1.0,1.0,28.0,1977,0.060753,B,B,15,2787,2,520.0,0,7,B,483283.488083
9682,8837,48,1.0,40.412437,11.617853,8.0,8.0,25.0,2011,0.041125,B,B,46,9515,5,NaN,1,10,B,259391.801748
9813,2040,62,1.0,122.438148,5.751401,1.0,2.0,3.0,1977,0.072158,B,B,2,629,1,NaN,0,0,A,224900.897679
9888,6053,6,1.0,41.314775,5.005477,1.0,9.0,17.0,2016,0.243205,B,B,5,1564,0,540.0,0,0,B,159149.515475

In [13]:
data.loc[data['Rooms']==1].describe()

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Social_1,Social_2,Social_3,Healthcare_1,Helthcare_2,Shops_1,Price
count,3705.000000,3705.000000,3705.0,3705.000000,2827.000000,3705.000000,3705.000000,3705.000000,3.705000e+03,3705.000000,3705.000000,3705.00000,3705.000000,1804.000000,3705.000000,3705.000000,3705.000000
mean,8406.774629,47.137652,1.0,41.323277,25.159008,6.525776,7.834278,13.927665,7.398392e+03,0.122414,23.470175,5108.68583,7.272874,1087.676275,1.202159,3.983266,159850.800729
std,4851.019498,40.832580,0.0,11.427651,14.202326,46.385219,5.363319,6.053992,3.293979e+05,0.122182,17.866805,4068.20106,23.371513,954.820718,1.458162,4.754359,51892.475206
min,0.000000,0.000000,1.0,1.136859,0.370619,0.000000,0.000000,1.000000,1.910000e+03,0.000000,0.000000,168.00000,0.000000,30.000000,0.000000,0.000000,60502.583500
25%,4063.000000,20.000000,1.0,36.692587,19.681268,1.000000,4.000000,9.000000,1.977000e+03,0.019509,5.000000,1564.00000,0.000000,520.000000,0.000000,0.000000,128711.103732
50%,8486.000000,30.000000,1.0,40.406590,21.663929,6.000000,7.000000,14.000000,1.977000e+03,0.075779,23.000000,5148.00000,1.000000,830.000000,1.000000,3.000000,154979.497993
75%,12628.000000,66.000000,1.0,43.565368,24.232240,8.000000,12.000000,17.000000,2.004000e+03,0.211401,35.000000,7065.00000,4.000000,1406.000000,2.000000,5.000000,182212.201038
max,16798.000000,209.000000,1.0,409.425181,410.639749,2014.000000,37.000000,99.000000,2.005201e+07,0.521867,74.000000,19083.00000,141.000000,4849.000000,6.000000,23.000000,594565.299770

In [20]:
data.describe()

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Social_1,Social_2,Social_3,Healthcare_1,Helthcare_2,Shops_1,Price
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.0,10000.000000,10000.00000,10000.000000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,5202.000000,10000.000000,10000.000000,10000.000000
mean,8383.40770,50.400800,1.890500,56.315775,14.0,6.273300,7.70040,13.435700,3.990166e+03,0.118858,24.687000,5352.157400,8.039200,1142.904460,1.319500,4.231300,214138.857399
std,4859.01902,43.587592,0.839512,21.058732,0.0,28.560917,5.30406,6.094012,2.005003e+05,0.119025,17.532614,4006.799803,23.831875,1021.517264,1.493601,4.806341,92872.293865
min,0.00000,0.000000,0.000000,1.136859,14.0,0.000000,0.00000,1.000000,1.910000e+03,0.000000,0.000000,168.000000,0.000000,0.000000,0.000000,0.000000,59174.778028
25%,4169.50000,20.000000,1.000000,41.774881,14.0,1.000000,4.00000,9.000000,1.974000e+03,0.017647,6.000000,1564.000000,0.000000,350.000000,0.000000,1.000000,153872.633942
50%,8394.50000,36.000000,2.000000,52.513310,14.0,6.000000,7.00000,14.000000,1.977000e+03,0.075424,25.000000,5285.000000,2.000000,900.000000,1.000000,3.000000,192269.644879
75%,12592.50000,75.000000,2.000000,65.900625,14.0,9.000000,11.00000,17.000000,2.001000e+03,0.195781,36.000000,7227.000000,5.000000,1548.000000,2.000000,6.000000,249135.462171
max,16798.00000,209.000000,19.000000,641.065193,14.0,2014.000000,42.00000,117.000000,2.005201e+07,0.521867,74.000000,19083.000000,141.000000,4849.000000,6.000000,23.000000,633233.466570

In [131]:
ls2 = data.loc[data['Rooms']==2].loc[data['LifeSquare'] < 10.5*2]

In [132]:
ls2['LifeSquare'] = 16*ls2['Rooms']

In [133]:
data.loc[data['Rooms']==2].loc[data['LifeSquare'] < 10.5*2] = ls2

In [129]:
ls3 = data.loc[data['Rooms']==3].loc[data['LifeSquare']<10.5*3]

In [130]:
ls3['LifeSquare'] = 14*ls3['Rooms']

In [140]:
data.loc[data['Rooms']==3].loc[data['LifeSquare']<10.5*3]=ls3

In [134]:
ls4 = data.loc[data['Rooms']==4].loc[data['LifeSquare']<10.5*4]

In [135]:
ls4['LifeSquare'] = 16*ls4['Rooms']

In [136]:
data.loc[data['Rooms']==4].loc[data['LifeSquare']<10.5*4] = ls4

In [137]:
ls5 = data.loc[data['Rooms']==5].loc[data['LifeSquare']<10.5*5]

In [138]:
ls5['LifeSquare'] = 16*ls5['Rooms']

In [139]:
data.loc[data['Rooms']==5].loc[data['LifeSquare']<10.5*5] = ls5

In [145]:
data.loc[data['Rooms']==1].loc[data['LifeSquare']<12] = ls1

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Healthcare_1,Helthcare_2,Shops_1,Shops_2,Price
160,3522,6,1.0,66.419841,3.987101,1.0,1.0,2.0,1977,0.243205,B,B,5,1564,0,540.0,0,0,B,193361.229815
270,15215,17,1.0,46.692974,5.941401,1.0,1.0,7.0,2015,0.000000,B,B,18,3374,5,620.0,1,2,B,212290.684086
363,15751,9,1.0,44.171793,1.251846,1.0,11.0,18.0,2017,0.161532,B,B,25,5648,1,30.0,2,4,B,134910.715588
477,8849,45,1.0,63.419553,2.286357,1.0,1.0,3.0,1977,0.195781,B,B,23,5212,6,NaN,3,2,B,325600.765809
527,2141,56,1.0,53.733677,4.323046,1.0,1.0,24.0,2015,0.000000,B,B,23,5067,4,NaN,2,6,B,208773.977243
674,10631,88,1.0,42.571618,1.941521,1.0,1.0,6.0,1977,0.127376,B,B,43,8429,3,NaN,3,9,B,130374.241595
695,1867,30,1.0,54.626206,4.651397,1.0,3.0,4.0,1977,0.000078,B,B,22,6398,141,1046.0,3,23,B,87456.520038
707,4345,62,1.0,49.275155,1.377284,1.0,1.0,5.0,2020,0.072158,B,B,2,629,1,NaN,0,0,A,135353.885620
734,4319,62,1.0,51.815214,4.203073,1.0,1.0,6.0,1977,0.072158,B,B,2,629,1,NaN,0,0,A,137880.620962
765,7060,27,1.0,38.651043,5.822657,1.0,7.0,17.0,1977,0.011654,B,B,4,915,0,NaN,0,0,B,103210.010325
850,2470,6,1.0,43.312025,1.404493,1.0,11.0,17.0,1977,0.243205,B,B,5,1564,0,540.0,0,0,B,128588.741321
1169,14866,6,1.0,38.818170,5.927865,1.0,17.0,18.0,1977,0.243205,B,B,5,1564,0,540.0,0,0,B,131405.866884
1175,3527,9,1.0,72.035396,2.358992,1.0,1.0,5.0,1977,0.161532,B,B,25,5648,1,30.0,2,4,B,191744.615408
1214,6366,6,1.0,47.804946,2.553024,1.0,6.0,25.0,1977,0.243205,B,B,5,1564,0,540.0,0,0,B,133552.372112
1316,11526,27,1.0,4.633498,1.969969,1.0,1.0,18.0,1977,0.011654,B,B,4,915,0,NaN,0,0,B,107604.269441
1410,1843,74,1.0,49.635712,3.411048,1.0,1.0,4.0,1977,0.309479,B,B,35,7715,4,990.0,0,6,B,146838.036852
1504,2967,1,1.0,62.494611,3.489694,0.0,0.0,1.0,1977,0.007122,B,B,1,264,0,NaN,0,1,B,193568.854208
1608,10202,6,1.0,2.596351,4.604943,1.0,3.0,25.0,2014,0.243205,B,B,5,1564,0,540.0,0,0,B,137597.601458
1673,12335,9,1.0,60.022123,2.858369,1.0,1.0,9.0,1977,0.161532,B,B,25,5648,1,30.0,2,4,B,176731.431750
1800,13113,27,1.0,37.805231,2.228592,11.0,0.0,6.0,2015,0.017647,B,B,2,469,0,NaN,0,0,B,137402.092529
1918,13603,63,1.0,127.651237,2.609712,1.0,8.0,17.0,2016,0.238617,B,B,26,3889,6,705.0,3,6,B,594565.299770
2224,3746,62,1.0,46.722042,1.944446,1.0,11.0,12.0,2018,0.072158,B,B,2,629,1,NaN,0,0,A,133721.121715
2309,10285,30,1.0,32.271741,3.386009,1.0,4.0,19.0,1977,0.000078,B,B,22,6398,141,1046.0,3,23,B,105921.018210
2418,5989,6,1.0,39.251773,2.981582,1.0,17.0,25.0,2016,0.243205,B,B,5,1564,0,540.0,0,0,B,136206.666782
2430,1317,6,1.0,51.460538,4.763693,1.0,25.0,25.0,1977,0.243205,B,B,5,1564,0,540.0,0,0,B,142065.034795
2665,8997,74,1.0,43.227719,1.726270,1.0,9.0,17.0,2016,0.075779,B,B,6,1437,3,NaN,0,2,B,154565.271940
2842,3142,6,1.0,39.145322,4.083905,1.0,8.0,17.0,1977,0.243205,B,B,5,1564,0,540.0,0,0,B,116981.443099
2860,12542,1,1.0,44.204418,1.789086,1.0,6.0,17.0,1977,0.007122,B,B,1,264,0,NaN,0,1,B,160181.048031
2898,5497,58,1.0,37.686426,4.977769,1.0,2.0,17.0,1977,0.437885,B,B,23,5735,3,1084.0,0,5,B,72950.870871
2906,10404,6,1.0,43.613432,3.668460,1.0,3.0,17.0,2016,0.243205,B,B,5,1564,0,540.0,0,0,B,128710.472293
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6609,13491,0,1.0,38.178277,0.370619,0.0,17.0,19.0,2016,0.006076,B,B,30,5285,0,645.0,6,6,B,105134.286994
7028,13440,6,1.0,78.432890,4.044174,1.0,1.0,2.0,1977,0.243205,B,B,5,1564,0,540.0,0,0,B,222826.758816
7045,15209,83,1.0,41.527079,2.077811,1.0,1.0,17.0,1977,0.007720,B,B,38,4788,2,NaN,0,4,B,214393.174037
7056,5575,27,1.0,41.941912,4.437475,0.0,0.0,10.0,2016,0.211401,B,B,9,1892,0,NaN,0,1,B,113350.022423
7068,15346,30,1.0,37.387578,4.699898,1.0,14.0,22.0,1977,0.000078,B,B,22,6398,141,1046.0,3,23,B,109553.129485
7221,5306,96,1.0,49.462997,1.417155,1.0,8.0,15.0,2016,0.041116,B,B,53,14892,4,NaN,1,4,B,119791.098164
7288,59,27,1.0,27.181473,10.924281,8.0,10.0,25.0,2014,0.072158,B,B,2,629,1,NaN,0,0,A,75170.813107
7452,8626,1,1.0,47.195748,1.168791,1.0,19.0,24.0,1977,0.007122,B,B,1,264,0,NaN,0,1,B,170718.296542
7719,10079,59,1.0,48.232741,3.288779,1.0,15.0,17.0,2017,0.019509,B,B,37,7687,11,176.0,5,5,B,207086.637307
7756,1680,58,1.0,47.889736,3.605019,1.0,3.0,17.0,1977,0.437885,B,B,23,5735,3,1084.0,0,5,B,122731.005950
7767,6927,21,1.0,16.117154,8.822988,0.0,2.0,5.0,1965,0.194489,B,B,47,8004,3,125.0,3,5,B,79913.267856
7897,10635,21,1.0,18.983962,11.419796,2.0,1.0,5.0,1967,0.194489,B,B,47,8004,3,125.0,3,5,B,112411.221700
8065,7669,34,1.0,43.873302,1.973848,1.0,13.0,17.0,2015,0.069753,B,B,53,13670,4,NaN,1,11,B,204863.503174
8220,8194,30,1.0,42.065862,5.624248,1.0,13.0,17.0,1977,0.000078,B,B,22,6398,141,1046.0,3,23,B,126976.982021
8283,15744,34,1.0,1.988943,2.642219,1.0,4.0,21.0,1977,0.069753,B,B,53,13670,4,NaN,1,11,B,458378.777006
8452,14380,58,1.0,40.525820,4.174627,1.0,16.0,17.0,1977,0.437885,B,B,23,5735,3,1084.0,0,5,B,116642.983817
8556,16575,27,1.0,32.712359,11.047605,13.0,8.0,25.0,2016,0.072158,B,B,2,629,1,NaN,0,0,A,94433.038958
8715,1936,74,1.0,53.835574,1.185864,0.0,7.0,7.0,2018,0.075779,B,B,6,1437,3,NaN,0,2,B,185976.351147
8886,2056,9,1.0,47.301790,5.125908,1.0,1.0,7.0,1977,0.161532,B,B,25,5648,1,30.0,2,4,B,138880.254465
8908,10684,22,1.0,41.872590,2.347250,1.0,1.0,3.0,1977,0.118537,B,B,30,6207,1,1183.0,1,0,B,136609.809831
9177,13951,45,1.0,39.225914,2.372105,1.0,24.0,24.0,2017,0.195781,B,B,23,5212,6,NaN,3,2,B,271893.118572
9192,1754,6,1.0,61.978423,3.943299,1.0,1.0,1.0,1977,0.243205,B,B,5,1564,0,540.0,0,0,B,177116.339701
9294,6782,45,1.0,2.954309,5.257278,1.0,1.0,3.0,1977,0.195781,B,B,23,5212,6,NaN,3,2,B,438005.182323
9299,8687,48,1.0,42.840915,2.608669,1.0,17.0,19.0,1977,0.041125,B,B,46,9515,5,NaN,1,10,B,236378.466217
9396,3745,30,1.0,42.457169,3.259832,1.0,10.0,25.0,2014,0.000078,B,B,22,6398,141,1046.0,3,23,B,155348.833619
9576,7389,23,1.0,52.028804,4.295819,0.0,8.0,9.0,1977,0.014073,B,B,2,475,0,NaN,0,0,B,98638.755928
9613,7657,38,1.0,4.502784,4.618547,1.0,1.0,28.0,1977,0.060753,B,B,15,2787,2,520.0,0,7,B,483283.488083
9682,8837,48,1.0,40.412437,11.617853,8.0,8.0,25.0,2011,0.041125,B,B,46,9515,5,NaN,1,10,B,259391.801748
9813,2040,62,1.0,122.438148,5.751401,1.0,2.0,3.0,1977,0.072158,B,B,2,629,1,NaN,0,0,A,224900.897679
9888,6053,6,1.0,41.314775,5.005477,1.0,9.0,17.0,2016,0.243205,B,B,5,1564,0,540.0,0,0,B,159149.515475